### ISSUE TITLE
Controlling AV over IP encoders/decoders

### ISSUE THREAD

**Issue by jpw547-zz** [byuoitav/atlona-microservice#7]
A little confused on the command interface... We were emailed one or two commands, that don't really help us. Can't seem to figure out how the websocket command structure works to work with other commands listed in Atlona's [API command list](https://atlona.com/pdf/AT-OMNI-1XX_API.PDF).

**Comment by cjreeder** [comment]
Most recent merge to master of VideoOverIP branch resolves this issue.  It's been added to master to allow for testing.
